jordancollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('jordans/', views.jordans_index, name='index'),
    path('jordans/<int:jordan_id>/', views.jordans_detail, name='detail'),
    path('jordans/create/', views.JordanCreate.as_view(), name = 'jordans_create'),
    path('jordans/<int:pk>/update/', views.JordanUpdate.as_view(), name = 'jordans_update'),
    path('jordans/<int:pk>/delete/', views.JordanDelete.as_view(), name = 'jordans_delete'),
    path('jordans/<int:jordan_id>/add_task/', views.add_task, name = 'add_task'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

ACTIONS =(
    ('c', 'Clean'),
    ('w', 'Wear')
)

# Create your models here.
class Jordan(models.Model):
    model = models.CharField(max_length=100)
    colorway = models.CharField(max_length=100)
    release_year = models.IntegerField()
    designer = models.CharField(max_length=100)
    materials = models.CharField(max_length=150)

#Changing this instance method does not impact the database therefore no make migrations is necessary
    def __str__(self) -> str:
        return f'{self.model} ({self.id})'
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'jordan_id': self.id})
    
class Task(models.Model):
    date = models.DateField('task date')
    action = models.CharField(
        max_length=1,
            choices=ACTIONS,
            default=ACTIONS[0][0]
        )
    
    jordan = models.ForeignKey(Jordan, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_action_display()} on {self.date}"
    
    class Meta:
        ordering =['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Task

class TaskForm(ModelForm):
  class Meta:
    model = Task
    fields = ['date', 'action']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, DeleteView

from .models import Jordan
from .forms import TaskForm

# Create your views here.

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def jordans_index(request):
    jordans= Jordan.objects.all()
    return render(request, 'jordans/index.html', {'jordans': jordans})

def jordans_detail(request, jordan_id):
    jordan = Jordan.objects.get(id=jordan_id)

    task_form = TaskForm()
    return render(request, 'jordans/detail.html', { 
        'jordan': jordan, 'task_form': task_form
    })

def add_task(request, jordan_id):
    form = TaskForm(request.POST)
    if form.is_valid():
        new_task = form.save(commit=False)
        new_task.jordan_id = jordan_id
        new_task.save()
    return redirect('detail', jordan_id=jordan_id)

class JordanCreate(CreateView):
    model = Jordan
    fields = '__all__'
    success_url = '/jordans/{jordan_id}'

class JordanUpdate(UpdateView):
    model = Jordan
    fields = ['colorway', 'materials']

class JordanDelete(DeleteView):
    model = Jordan
    success_url = '/jordans'

Python-3.11.0/Doc/tools/templates/customsourcelink.html
{%- if show_source and has_source and sourcename %}
  <div role="note" aria-label="source link">
    <h3>{{ _('This Page') }}</h3>
    <ul class="this-page-menu">
      <li><a href="{{ pathto('bugs') }}">{% trans %}Report a Bug{% endtrans %}</a></li>
      <li>
        <a href="https://github.com/python/cpython/blob/main/Doc/{{ sourcename|replace('.rst.txt', '.rst') }}"
            rel="nofollow">{{ _('Show Source') }}
        </a>
      </li>
    </ul>
  </div>
{%- endif %}

Python-3.11.0/Doc/tools/templates/download.html
{% extends "layout.html" %}
{% set title = 'Download' %}
{% if daily is defined %}
  {% set dlbase = pathto('archives', 1) %}
{% else %}
  {#
    The link below returns HTTP 404 until the first related alpha release.
    This is expected; use daily documentation builds for CPython development.
  #}
  {% set dlbase = 'https://docs.python.org/ftp/python/doc/' + release %}
{% endif %}

{% block body %}
<h1>Download Python {{ release }} Documentation</h1>

{% if last_updated %}<p><b>Last updated on: {{ last_updated }}.</b></p>{% endif %}

<p>To download an archive containing all the documents for this version of
Python in one of various formats, follow one of links in this table.</p>

<table class="docutils">
  <tr><th>Format</th><th>Packed as .zip</th><th>Packed as .tar.bz2</th></tr>
  <tr><td>PDF (US-Letter paper size)</td>
    <td><a href="{{ dlbase }}/python-{{ release }}-docs-pdf-letter.zip">Download</a> (ca. 13 MiB)</td>
    <td><a href="{{ dlbase }}/python-{{ release }}-docs-pdf-letter.tar.bz2">Download</a> (ca. 13 MiB)</td>
  </tr>
  <tr><td>PDF (A4 paper size)</td>
    <td><a href="{{ dlbase }}/python-{{ release }}-docs-pdf-a4.zip">Download</a> (ca. 13 MiB)</td>
    <td><a href="{{ dlbase }}/python-{{ release }}-docs-pdf-a4.tar.bz2">Download</a> (ca. 13 MiB)</td>
  </tr>
  <tr><td>HTML</td>
    <td><a href="{{ dlbase }}/python-{{ release }}-docs-html.zip">Download</a> (ca. 9 MiB)</td>
    <td><a href="{{ dlbase }}/python-{{ release }}-docs-html.tar.bz2">Download</a> (ca. 6 MiB)</td>
  </tr>
  <tr><td>Plain Text</td>
    <td><a href="{{ dlbase }}/python-{{ release }}-docs-text.zip">Download</a> (ca. 3 MiB)</td>
    <td><a href="{{ dlbase }}/python-{{ release }}-docs-text.tar.bz2">Download</a> (ca. 2 MiB)</td>
  </tr>
 <tr><td>EPUB</td>
    <td><a href="{{ dlbase }}/python-{{ release }}-docs.epub">Download</a> (ca. 5 MiB)</td>
    <td></td>
  </tr>
</table>

<p>These archives contain all the content in the documentation.</p>


<h2>Unpacking</h2>

<p>Unix users should download the .tar.bz2 archives; these are bzipped tar
archives and can be handled in the usual way using tar and the bzip2
program. The <a href="http://www.info-zip.org">InfoZIP</a> unzip program can be
used to handle the ZIP archives if desired. The .tar.bz2 archives provide the
best compression and fastest download times.</p>

<p>Windows users can use the ZIP archives since those are customary on that
platform. These are created on Unix using the InfoZIP zip program.</p>


<h2>Problems</h2>

<p>If you have comments or suggestions for the Python documentation, please send
email to <a href="mailto:docs@python.org">docs@python.org</a>.</p>
{% endblock %}

Python-3.11.0/Doc/tools/templates/dummy.html
This file is not an actual template, but used to add some
texts in extensions to sphinx.pot file.

In extensions/pyspecific.py:

{% trans %}CPython implementation detail:{% endtrans %}
{% trans %}Deprecated since version {deprecated}, will be removed in version {removed}{% endtrans %}
{% trans %}Deprecated since version {deprecated}, removed in version {removed}{% endtrans %}


In docsbuild-scripts, when rewriting indexsidebar.html with actual versions:

{% trans %}in development{% endtrans %}
{% trans %}pre-release{% endtrans %}
{% trans %}stable{% endtrans %}
{% trans %}security-fixes{% endtrans %}
{% trans %}EOL{% endtrans %}

Python-3.11.0/Doc/tools/templates/indexcontent.html
{% extends "layout.html" %}
{%- block htmltitle -%}
<title>{{ shorttitle }}</title>
{%- endblock -%}
{% block body %}
  <h1>{{ docstitle|e }}</h1>
  <p>
  {% trans %}Welcome! This is the official documentation for Python {{ release }}.{% endtrans %}
  </p>
  <p><strong>{% trans %}Parts of the documentation:{% endtrans %}</strong></p>
  <table class="contentstable" align="center"><tr>
    <td width="50%">
      <p class="biglink"><a class="biglink" href="{{ pathto("whatsnew/" + version) }}">{% trans %}What's new in Python {{ version }}?{% endtrans %}</a><br/>
        <span class="linkdescr"> {% trans whatsnew_index=pathto("whatsnew/index") %}or <a href="{{ whatsnew_index }}">all "What's new" documents</a> since 2.0{% endtrans %}</span></p>
      <p class="biglink"><a class="biglink" href="{{ pathto("tutorial/index") }}">{% trans %}Tutorial{% endtrans %}</a><br/>
         <span class="linkdescr">{% trans %}start here{% endtrans %}</span></p>
      <p class="biglink"><a class="biglink" href="{{ pathto("library/index") }}">{% trans %}Library Reference{% endtrans %}</a><br/>
         <span class="linkdescr">{% trans %}keep this under your pillow{% endtrans %}</span></p>
      <p class="biglink"><a class="biglink" href="{{ pathto("reference/index") }}">{% trans %}Language Reference{% endtrans %}</a><br/>
         <span class="linkdescr">{% trans %}describes syntax and language elements{% endtrans %}</span></p>
      <p class="biglink"><a class="biglink" href="{{ pathto("using/index") }}">{% trans %}Python Setup and Usage{% endtrans %}</a><br/>
         <span class="linkdescr">{% trans %}how to use Python on different platforms{% endtrans %}</span></p>
      <p class="biglink"><a class="biglink" href="{{ pathto("howto/index") }}">{% trans %}Python HOWTOs{% endtrans %}</a><br/>
         <span class="linkdescr">{% trans %}in-depth documents on specific topics{% endtrans %}</span></p>
    </td><td width="50%">
      <p class="biglink"><a class="biglink" href="{{ pathto("installing/index") }}">{% trans %}Installing Python Modules{% endtrans %}</a><br/>
         <span class="linkdescr">{% trans %}installing from the Python Package Index &amp; other sources{% endtrans %}</span></p>
      <p class="biglink"><a class="biglink" href="{{ pathto("distributing/index") }}">{% trans %}Distributing Python Modules{% endtrans %}</a><br/>
         <span class="linkdescr">{% trans %}publishing modules for installation by others{% endtrans %}</span></p>
      <p class="biglink"><a class="biglink" href="{{ pathto("extending/index") }}">{% trans %}Extending and Embedding{% endtrans %}</a><br/>
         <span class="linkdescr">{% trans %}tutorial for C/C++ programmers{% endtrans %}</span></p>
      <p class="biglink"><a class="biglink" href="{{ pathto("c-api/index") }}">{% trans %}Python/C API{% endtrans %}</a><br/>
         <span class="linkdescr">{% trans %}reference for C/C++ programmers{% endtrans %}</span></p>
      <p class="biglink"><a class="biglink" href="{{ pathto("faq/index") }}">{% trans %}FAQs{% endtrans %}</a><br/>
         <span class="linkdescr">{% trans %}frequently asked questions (with answers!){% endtrans %}</span></p>
    </td></tr>
  </table>

  <p><strong>{% trans %}Indices and tables:{% endtrans %}</strong></p>
  <table class="contentstable" align="center"><tr>
    <td width="50%">
      <p class="biglink"><a class="biglink" href="{{ pathto("py-modindex") }}">{% trans %}Global Module Index{% endtrans %}</a><br/>
         <span class="linkdescr">{% trans %}quick access to all modules{% endtrans %}</span></p>
      <p class="biglink"><a class="biglink" href="{{ pathto("genindex") }}">{% trans %}General Index{% endtrans %}</a><br/>
         <span class="linkdescr">{% trans %}all functions, classes, terms{% endtrans %}</span></p>
      <p class="biglink"><a class="biglink" href="{{ pathto("glossary") }}">{% trans %}Glossary{% endtrans %}</a><br/>
         <span class="linkdescr">{% trans %}the most important terms explained{% endtrans %}</span></p>
    </td><td width="50%">
      <p class="biglink"><a class="biglink" href="{{ pathto("search") }}">{% trans %}Search page{% endtrans %}</a><br/>
         <span class="linkdescr">{% trans %}search this documentation{% endtrans %}</span></p>
      <p class="biglink"><a class="biglink" href="{{ pathto("contents") }}">{% trans %}Complete Table of Contents{% endtrans %}</a><br/>
         <span class="linkdescr">{% trans %}lists all sections and subsections{% endtrans %}</span></p>
    </td></tr>
  </table>

  <p><strong>{% trans %}Meta information:{% endtrans %}</strong></p>
  <table class="contentstable" align="center"><tr>
    <td width="50%">
      <p class="biglink"><a class="biglink" href="{{ pathto("bugs") }}">{% trans %}Reporting bugs{% endtrans %}</a></p>
      <p class="biglink"><a class="biglink" href="https://devguide.python.org/docquality/#helping-with-documentation">{% trans %}Contributing to Docs{% endtrans %}</a></p>
      <p class="biglink"><a class="biglink" href="{{ pathto("about") }}">{% trans %}About the documentation{% endtrans %}</a></p>
    </td><td width="50%">
      <p class="biglink"><a class="biglink" href="{{ pathto("license") }}">{% trans %}History and License of Python{% endtrans %}</a></p>
      <p class="biglink"><a class="biglink" href="{{ pathto("copyright") }}">{% trans %}Copyright{% endtrans %}</a></p>
    </td></tr>
  </table>
{% endblock %}

Python-3.11.0/Doc/tools/templates/indexsidebar.html
<h3>{% trans %}Download{% endtrans %}</h3>
<p><a href="{{ pathto('download') }}">{% trans %}Download these documents{% endtrans %}</a></p>
<h3>{% trans %}Docs by version{% endtrans %}</h3>
<ul>
  <li><a href="https://docs.python.org/">{% trans %}Stable{% endtrans %}</a></li>
  <li><a href="https://docs.python.org/dev/">{% trans %}In development{% endtrans %}</a></li>
  <li><a href="https://www.python.org/doc/versions/">{% trans %}All versions{% endtrans %}</a></li>
</ul>

<h3>{% trans %}Other resources{% endtrans %}</h3>
<ul>
  {# XXX: many of these should probably be merged in the main docs #}
  <li><a href="https://peps.python.org/">{% trans %}PEP Index{% endtrans %}</a></li>
  <li><a href="https://wiki.python.org/moin/BeginnersGuide">{% trans %}Beginner's Guide{% endtrans %}</a></li>
  <li><a href="https://wiki.python.org/moin/PythonBooks">{% trans %}Book List{% endtrans %}</a></li>
  <li><a href="https://www.python.org/doc/av/">{% trans %}Audio/Visual Talks{% endtrans %}</a></li>
  <li><a href="https://devguide.python.org/">{% trans %}Python Developer’s Guide{% endtrans %}</a></li>
</ul>

Python-3.11.0/Doc/tools/templates/layout.html
{% extends "!layout.html" %}

{% block header %}
{%- if outdated %}
<div id="outdated-warning" style="padding: .5em; text-align: center; background-color: #FFBABA; color: #6A0E0E;">
    {% trans %}This document is for an old version of Python that is no longer supported.
    You should upgrade, and read the {% endtrans %}
    <a href="/3/{{ pagename }}{{ file_suffix }}">{% trans %} Python documentation for the current stable release{% endtrans %}</a>.
</div>
{%- endif %}
{% endblock %}

{% block rootrellink %}
{{ super() }}
    <li id="cpython-language-and-version">
      <a href="{{ pathto('index') }}">{{ shorttitle }}</a>{{ reldelim1 }}
    </li>
{% endblock %}

{% block extrahead %}
    <link rel="canonical" href="https://docs.python.org/3/{{pagename}}.html" />
    {% if builder != "htmlhelp" %}
      {% if pagename == 'whatsnew/changelog' and not embedded %}
      <script type="text/javascript" src="{{ pathto('_static/changelog_search.js', 1) }}"></script>{% endif %}
    {% endif %}

    {# custom CSS; used in asyncio docs! #}
    <style>
      @media only screen {{ "{" }}
        table.full-width-table {{ "{" }}
            width: 100%;
        {{ "}" }}
      {{ "}" }}
    </style>
{{ super() }}
{% endblock %}

Python-3.11.0/Doc/tools/templates/search.html
{% extends "!search.html" %}
{% block extrahead %}
    {{ super() }}
    <script type="text/javascript">
        var GLOSSARY_PAGE = 'glossary.html';

        jQuery(function() {
            $.getJSON("_static/glossary.json", function(glossary) {
                var RESULT_TEMPLATE = '<div style="display: none" class="admonition seealso" id="glossary-result">' +
                                      '  <p class="topic-title">' +
                                      '    <a class="glossary-title" href="#"></a>' +
                                      '  </p>' +
                                      '  <div class="glossary-body"></div>' +
                                      '</div>';
                $("#search-results").prepend(RESULT_TEMPLATE);

                var params = $.getQueryParameters();
                if (params.q) {
                    var search_param = params.q[0].toLowerCase();
                    var glossary_item = glossary[search_param];
                    if (glossary_item) {
                        var resultDiv = $("#glossary-result");

                        // set up the title text with a link to the glossary page
                        resultDiv.find(".glossary-title").text('Glossary: ' + glossary_item.title);
                        var link_target = search_param.replace(/ /g, '-');
                        resultDiv.find(".glossary-title").attr(
                            'href', GLOSSARY_PAGE + '#term-' + link_target
                        );

                        // rewrite any anchor links (to other glossary terms)
                        // to have a full reference to the glossary page
                        var body = $(glossary_item.body).children();
                        body.find("a[href^='#']").each(function() {
                            var current_url = $(this).attr('href');
                            $(this).attr('href', GLOSSARY_PAGE + current_url);
                        });
                        resultDiv.find(".glossary-body").html(body);

                        resultDiv.show();
                    } else {
                        $("#glossary-result").hide('');
                    }
                }
            });
        });
    </script>
{% endblock %}

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}


<div class="image-wrapper center-align">
    <img src="../static/css/media/duo_jordan.jpg" alt="">
</div>
<p class="flow-text center-align">
    Welcome to Jordan Collector, the ultimate haven for Air Jordan enthusiasts! Immerse yourself in a community of sneaker lovers where you can log and showcase your treasured Air Jordans. With our user-friendly platform, effortlessly track your collection, and never miss a moment with personalized tasks to wear or clean your Js. Elevate your passion for Jordans to new heights - start your journey with Jordan Collector today!
</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jordan Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav>
        <div class = 'nav-wrapper red accent-4'>
            <ul class="left">
                <li>  <a href="{% url 'home' %}"> Home</a> </li>
            </ul>
            <ul class ='right'>
                <li>
                    <a href="{% url 'about' %}">About</a>
                </li>
                <li>
                    <a href="{% url 'jordans_create' %}">Add Jordans</a>
                </li>
                <li>
                    <a href="{% url 'index' %}">All Jordans</a>
                </li>
            </ul>
        </div>
    </nav>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
    <footer></footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1 class="center-align">Jordan Collector</h1>
<div class="center-align">
    <img class='responsive-img' src="../static/css/media/Jordan_hero.jpg" alt="">
</div>
{% endblock %}

main_app/templates/jordans/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Jordan Details</h1>

<div class="card">
  <div class="card-content">
    <span class="card-title red-text text-darken-4">{{ jordan.model }}</span>
    <p>Colorway: {{ jordan.colorway }}</p>
    <p>Release Year: {{ jordan.release_year}}</p>
    <p>Designer: {{jordan.designer}} </p>
    <p>Materials: {{jordan.materials}}</p>
  </div>
  <div class="card-action red accent-4">
    <a href="{% url 'jordans_update' jordan.id%}" class="white-text">Edit</a>
    <a href="{% url 'jordans_delete' jordan.id%}" class="white-text">Delete</a>
  </div>
</div>

<div>
  <form action="{% url 'add_task' jordan.id %}" method="POST">
    {% csrf_token %}
    {{ task_form.as_p}}
    <input type="submit" class="btn red accent-4" value="Add Task">
  </form>
  <table>
    <thead>
      <tr class="red-text"><th>Date</th><th>Task</th></tr>
    </thead>
    <tbody>
      {% for task in jordan.task_set.all %}
        <tr>
          <td>{{task.date}}</td>
          <td>{{task.get_action_display}}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

main_app/templates/jordans/index.html
{% extends 'base.html' %}
{% block content %}

<h2>My Jordans:</h2>

{% for jordan in jordans %}
<div class="card red darken-3">
    <div class="card-content white-text">
        <a href="{% url 'detail' jordan.id %}" class="white-text">
            <p><span class='card-title'> Model: {{jordan.model}}</span></p>
            <p>Colorway: {{jordan.colorway}}</p>
            <p>Release Year: {{jordan.release_year}}</p>
            <p>Designer: {{jordan.designer}}</p>
            <p>Material: {{jordan.materials}}</p>
       </a>
    </div>
</div>
{% endfor %}

{% endblock %}

main_app/templates/main_app/jordan_confirm_delete.html
{%extends 'base.html' %}

{% block content %}
    <h1 class="red-text text-darken-4">Delete Jordan</h1>

    <h4>Are you sure you want to delete <span>{{ object.model}} {{object.colorway}}</span>?</h4>

    <form action="" method="POST">
      {% csrf_token %}
      <input type="submit" value="Yes - Delete!" class="btn-large red accent-4 right">
      <a href="{% url 'detail' jordan.id %}"class='grey-text'>Cancel</a>
    </form>
  {% endblock %}

main_app/templates/main_app/jordan_form.html
{% extends 'base.html' %}

{% block content %}
    {% if object %}
    <h1 class="red-text text-darken-4">Edit <span>{{object.model}}</span></h1>
    {% else %}
     <h1 class="red-text text-darken-4">Add Jordan</h1>
    {% endif %}

    <form action="" method="POST">

        {% csrf_token %}
        <table>
 
    {{ form.as_table }}      
        </table>

        <button class="btn-large red accent-4 right" type="submit" name="action">
       SUBMIT!
        </button>
        <!-- <input type="submit" value="Submit!" class="btn"> -->
    </form>
{% endblock %}